@EventManagement_HostAddress = http://localhost:5009
@Events_Endpoint = events

### Get All Events
GET {{EventManagement_HostAddress}}/{{Events_Endpoint}}
Accept: application/json

### Create a new Event
POST {{EventManagement_HostAddress}}/{{Events_Endpoint}}
Content-Type: application/json

{
  "name": "Building AI Apps with a Roadmap",
  "description": "",
  "location": "Detriot, Texas",
  "pricePerPerson": 189.65,
  "date": "2025-12-20T09:00:00Z"
}

### Update an Event
PUT {{EventManagement_HostAddress}}/{{Events_Endpoint}}/ec0d50d6-24af-431b-bfd0-b7bb6e961bc7
Content-Type: application/json

{
  "name": "AI Developer Conf",
  "location": "Los Angeles",
  "date": "2025-09-01T10:00:00Z",
  "pricePerPerson": 125.65
}

### Delete an Event
DELETE {{EventManagement_HostAddress}}/{{Events_Endpoint}}/0cbe2d2b-2bcf-4c83-8577-1bc90adff569

### Delete all events
DELETE {{EventManagement_HostAddress}}/{{Events_Endpoint}}